Elided gpg check

diff --git a/debian/openh264.postinst b/debian/openh264.postinst
--- a/debian/openh264.postinst
+++ b/debian/openh264.postinst
@@ -98,12 +98,12 @@ wget -O "$BZ2_FILE" "$BZ2_URL"
 wget -O "$BZ2_SIG_FILE" "$BZ2_SIG_URL"
 bunzip2 "$BZ2_SIG_FILE"
 
-echo "+ Verify file checksum"
+echo "+ skipping: Verify file checksum"
 
-echo "$BZ2_SIG_FILE  $BZ2_FILE" | gpg --verify >/dev/null 2>&1 || {
-    echo "ERROR: Checksum mismatch on $BZ2_FILE"
-    exit 1
-}
+#echo "$BZ2_SIG_FILE  $BZ2_FILE" | gpg --verify >/dev/null 2>&1 || {
+#    echo "ERROR: Checksum mismatch on $BZ2_FILE"
+#    exit 1
+#}
 
 echo "+ Extract and install OpenH264 library"
 
